// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Solo soportamos Android por ahora
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'Esta aplicación solo está configurada para Android.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz-o8QzaQIoNTAMz8oDmSg-lSlrnIYk6E',
    appId: '1:865035022869:android:02ae68ed4db1f745f2941c',
    messagingSenderId: '865035022869',
    projectId: 'ecotrack-app-23a64',
    storageBucket: 'ecotrack-app-23a64.firebasestorage.app',
  );
}